"use strict";
const WORDS=[
 {word:"FASZIEN",label:"Faszien",definition:"Ein körperweites Netzwerk aus Bindegewebe, das Strukturen verbindet, umhüllt und an Kraftübertragung sowie Wahrnehmung beteiligt ist."},
 {word:"KOLLAGEN",label:"Kollagen",definition:"Lange, zugfeste Fasern des Bindegewebes. Sie geben Haut, Sehnen, Bändern, Knorpel, Knochen und Organen Form und Stabilität."},
 {word:"FIBROBLASTEN",label:"Fibroblasten",definition:"Zellen des Bindegewebes, die Grundsubstanz und Kollagen bilden und bei Regeneration sowie Wundheilung eine Schlüsselrolle haben."},
 {word:"TENSEGRITAET",label:"Tensegrität",definition:"Ein Bauprinzip, bei dem Zug- und Druckkräfte über die gesamte Struktur verteilt und ausbalanciert werden."},
 {word:"THIXOTROPIE",label:"Thixotropie",definition:"Die Eigenschaft des Bindegewebes, durch Bewegung flüssiger zu werden und sich bei Ruhe stärker zu verfestigen."},
 {word:"DILATANZ",label:"Dilatanz",definition:"Bei schnellem oder starkem Druck steigt der Widerstand des Gewebes; es verhält sich vorübergehend fester und kann Stöße abpuffern."},
 {word:"INTEROZEPTION",label:"Interozeption",definition:"Die Wahrnehmung dessen, was im eigenen Körper vor sich geht. Sie ist wichtig für Homöostase, Gefühle und leibliches Selbsterleben."},
 {word:"RUFFINI",label:"Ruffini-Rezeptoren",definition:"Langsam adaptierende Mechanorezeptoren, die auch auf ruhige Griffe und besonders auf tangentiale Dehnung ansprechen."},
 {word:"PACINI",label:"Pacini-Rezeptoren",definition:"Mechanorezeptoren mit niedriger Reizschwelle, die rasch adaptieren und vor allem auf schnelle Druck- und Bewegungsänderungen reagieren."},
 {word:"GRUNDSUBSTANZ",label:"Grundsubstanz",definition:"Die flüssige bis zähflüssige Umgebung der Körperzellen, in der Stoffaustausch und viele außerzelluläre Vorgänge stattfinden."}
];
const SIZE=15,DIRECTIONS=[[0,1],[1,0],[1,1],[1,-1],[0,-1],[-1,0],[-1,-1],[-1,1]],ALPHABET="ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const gridEl=document.getElementById("grid"),wordListEl=document.getElementById("wordList"),foundCountEl=document.getElementById("foundCount"),statusEl=document.getElementById("status"),rabbit=document.getElementById("rabbit"),path=document.getElementById("path");
const learningModal=document.getElementById("learningModal"),finishModal=document.getElementById("finishModal"),cardTitle=document.getElementById("cardTitle"),cardDefinition=document.getElementById("cardDefinition"),pointsMessage=document.getElementById("pointsMessage");
let grid=[],placements=[],found=new Set(),dragging=false,startCell=null,currentSelection=[];
function rand(n){return Math.floor(Math.random()*n)}
function makeGrid(){grid=Array.from({length:SIZE},()=>Array(SIZE).fill(""));placements=[];const ordered=[...WORDS].sort((a,b)=>b.word.length-a.word.length);for(const item of ordered){let placed=false;for(let tries=0;tries<800&&!placed;tries++){const [dr,dc]=DIRECTIONS[rand(DIRECTIONS.length)],r=rand(SIZE),c=rand(SIZE),endR=r+dr*(item.word.length-1),endC=c+dc*(item.word.length-1);if(endR<0||endR>=SIZE||endC<0||endC>=SIZE)continue;let ok=true;for(let i=0;i<item.word.length;i++){const existing=grid[r+dr*i][c+dc*i];if(existing&&existing!==item.word[i]){ok=false;break}}if(!ok)continue;const cells=[];for(let i=0;i<item.word.length;i++){const rr=r+dr*i,cc=c+dc*i;grid[rr][cc]=item.word[i];cells.push(`${rr}-${cc}`)}placements.push({item,cells});placed=true}if(!placed){makeGrid();return}}
 for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++)if(!grid[r][c])grid[r][c]=ALPHABET[rand(ALPHABET.length)];renderGrid()}
function renderGrid(){gridEl.innerHTML="";gridEl.style.setProperty("--size",SIZE);for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++){const cell=document.createElement("div");cell.className="cell";cell.dataset.r=r;cell.dataset.c=c;cell.dataset.key=`${r}-${c}`;cell.textContent=grid[r][c];cell.setAttribute("role","gridcell");gridEl.appendChild(cell)}}
function renderWords(){wordListEl.innerHTML="";WORDS.forEach(w=>{const el=document.createElement("div");el.className=`word-item${found.has(w.word)?" found":""}`;el.dataset.word=w.word;el.textContent=w.label;wordListEl.appendChild(el)});foundCountEl.textContent=found.size}
function renderPath(){path.innerHTML="";for(let i=0;i<=10;i++){const dot=document.createElement("span");dot.className=`path-dot${i<=found.size?" done":""}`;dot.style.left=`${i*10}%`;path.appendChild(dot)}const pct=4+(found.size/10)*88;rabbit.classList.add("hop");rabbit.style.left=`${pct}%`;setTimeout(()=>rabbit.classList.remove("hop"),680)}
function cellsOnLine(a,b){const dr=b.r-a.r,dc=b.c-a.c,steps=Math.max(Math.abs(dr),Math.abs(dc));if(steps===0)return [`${a.r}-${a.c}`];if(!(dr===0||dc===0||Math.abs(dr)===Math.abs(dc)))return[];const sr=Math.sign(dr),sc=Math.sign(dc),arr=[];for(let i=0;i<=steps;i++)arr.push(`${a.r+sr*i}-${a.c+sc*i}`);return arr}
function clearSelecting(){document.querySelectorAll(".cell.selecting").forEach(c=>c.classList.remove("selecting"))}
function paintSelection(keys){clearSelecting();keys.forEach(k=>document.querySelector(`[data-key="${k}"]`)?.classList.add("selecting"));currentSelection=keys}
function getCellFromPoint(x,y){const el=document.elementFromPoint(x,y);if(!el?.classList.contains("cell"))return null;return{r:+el.dataset.r,c:+el.dataset.c}}
function begin(cell){dragging=true;startCell=cell;paintSelection([`${cell.r}-${cell.c}`])}
function move(cell){if(!dragging||!startCell)return;paintSelection(cellsOnLine(startCell,cell))}
function end(){if(!dragging)return;dragging=false;const match=placements.find(p=>!found.has(p.item.word)&&(same(currentSelection,p.cells)||same(currentSelection,[...p.cells].reverse())));clearSelecting();if(match)foundWord(match);else if(currentSelection.length>1){statusEl.textContent="Dieses Wort gehört nicht zur Suchliste. Versuch es noch einmal."}currentSelection=[];startCell=null}
function same(a,b){return a.length===b.length&&a.every((v,i)=>v===b[i])}
function foundWord(match){found.add(match.item.word);match.cells.forEach(k=>document.querySelector(`[data-key="${k}"]`)?.classList.add("found"));renderWords();renderPath();statusEl.textContent=`Gefunden: ${match.item.label}!`;cardTitle.textContent=match.item.label;cardDefinition.textContent=match.item.definition;setTimeout(()=>{learningModal.hidden=false;document.getElementById("continueButton").focus()},520)}
function finish(){rabbit.src="assets/kaninchen-sitzend.png";rabbit.classList.add("sitting");rabbit.style.left="92%";const result=window.ZITPoints?.award("faszien-labyrinth",10,"Faszien-Labyrinth");pointsMessage.textContent=result&&!result.awarded?"10 Punkte bereits gesammelt":"10 von 10 Punkten";setTimeout(()=>{finishModal.hidden=false;document.getElementById("playAgainButton").focus()},900)}
function reset(){found=new Set();rabbit.src="assets/kaninchen-huepfend.png";rabbit.classList.remove("sitting");statusEl.textContent="Du kannst waagerecht, senkrecht oder diagonal suchen – auch rückwärts.";learningModal.hidden=true;finishModal.hidden=true;makeGrid();renderWords();renderPath()}
gridEl.addEventListener("pointerdown",e=>{const cell=e.target.closest(".cell");if(!cell)return;e.preventDefault();gridEl.setPointerCapture?.(e.pointerId);begin({r:+cell.dataset.r,c:+cell.dataset.c})});gridEl.addEventListener("pointermove",e=>{if(!dragging)return;const cell=getCellFromPoint(e.clientX,e.clientY);if(cell)move(cell)});gridEl.addEventListener("pointerup",end);gridEl.addEventListener("pointercancel",end);
document.getElementById("continueButton").addEventListener("click",()=>{learningModal.hidden=true;if(found.size===WORDS.length)finish()});document.getElementById("resetButton").addEventListener("click",reset);document.getElementById("playAgainButton").addEventListener("click",reset);reset();
